    puts "2 eh maior que 1= #{2>1}" 
""
    puts "2 eh maior que 1= #{2<1}" 
""
    puts "2 eh maior que 2= #{2==1}" 
""
    puts "2 eh maior que 1= #{2>=1}" 
""
    puts "2 eh maior que 1= #{2<=1}" 
""
    puts "2 eh maior que 1= #{2!=1}" 
""
    puts "2 eh maior que 1= #{4<=>3}" 
""
    puts "2 eh maior que 1= #{2<=>2}"
""
    puts "2 eh maior que 1= #{1<=>2}" 